POST http://localhost:3035/alert
Content-Type: application/json
Accept: application/json

{
  "title": "Esto es una alerta",
  "message": "Esto es una alerta",
  "chatId": 1547430999
}

###
POST http://localhost:3035/createIntegration
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaGF0SWQiOjE1NDc0MzA5OTksInNjb3BlIjoidGVtcG9yYWwtdG9rZW4iLCJzdGF0dXMiOiJhY3RpdmUiLCJpYXQiOjE3Njg2OTg3ODgsImV4cCI6MTc2ODY5OTA4OH0.Rez1GlvihH1OfJl3W43ylZMdTjq0RIV_dPOuAxy0W0U

{
  "chatId": 1547430999,
  "scope": "test"
}

###
GET http://localhost:3035/integrations/1547430999
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaGF0SWQiOjE1NDc0MzA5OTksInNjb3BlIjoidGVzdCIsInN0YXR1cyI6ImFjdGl2ZSIsImlhdCI6MTc2ODY5ODgxOH0.A4jFBH8pQbbEWPr25q0QIXfbHZNFxhOmiDp30o01QO0

###
POST http://localhost:3035/revokeIntegration
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaGF0SWQiOjE1NDc0MzA5OTksInNjb3BlIjoiYWxsIiwic3RhdHVzIjoiYWN0aXZlIiwiaWF0IjoxNzY4MDE2OTEzfQ.x8vQMDLICa9d_V2gseBSLx_cMJdqyb4pXo4neVr-TjI

{
  "chatId": 1547430999
}
###
POST http://localhost:3035/update-rate-limit
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaGF0SWQiOjE1NDc0MzA5OTksInNjb3BlIjoidGVzdCIsInN0YXR1cyI6ImFjdGl2ZSIsImlhdCI6MTc2ODY5ODgxOH0.A4jFBH8pQbbEWPr25q0QIXfbHZNFxhOmiDp30o01QO0

{
  "chatId": 1547430999
}
###